services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wendall\IbexaFormBuilderRecaptcha\FormBuilder\Field\Mapper\ReCaptchaMapper:
        arguments:
            $fieldIdentifier: 'recaptcha'
            $formType: 'Wendall\IbexaFormBuilderRecaptcha\Form\Type\ReCaptchaFieldType'
        tags:
            - { name: ibexa.form_builder.field_mapper }
